services:
  spring-api:
    build: .
    container_name: spring-api
    ports:
      - 8080:8080


  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.3
    ports:
      - 8081:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    volumes:
      - keycloak_data:/opt/keycloak/data
    command:
      - 'start-dev'

volumes:
  keycloak_data: